argo-cd:
  enabled: true
  rbac:
    create: true
  configs:
    params:
      server.insecure: true
    cm:
      timeout.reconciliation: 43200s
      url: https://argo-cd.theoffice.uk
      oidc.config: |
        name: Auth0
        issuer: https://dev-vjmj8roq7qd1h82m.uk.auth0.com/
        clientID: t4clTNxScIqcWhlCX8UUYrBJTQUeZv3H
        clientSecret: $argocd-oauth:oidc
        requestedScopes:
          - openid
          - profile
          - email
    rbac:
      create: true
      policy.default: role:readonly
      scopes: "[email, profile, openid]"
      policy.csv: |
        p, role:admin, applications, *, */*, allow
        p, role:admin, clusters, *, *, allow
        p, role:admin, repositories, *, *, allow
        p, role:admin, projects, *, *, allow
        p, role:admin, exec, create, */*, allow
        p, role:admin, logs, get, */*, allow
        p, role:admin, settings, *, *, allow
        g, admin, role:admin
        g, maxherbs10@gmail.com, role:admin

ingress:
  enabled: true
  className: traefik
  host: argo-cd.theoffice.uk
  tlsSecret: tls-argocd
