server: https://kubernetes.default.svc

argocd:
  enabled: true
  targetRevision: argocd

keycloak:
  enabled: false
  targetRevision: argocd

localPathStorage:
  enabled: true
  targetRevision: v0.0.31
  valuesObject:
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /var/local-path-provisioner
    storageClass:
      defaultClass: true
