apiVersion: v1
kind: Secret
metadata:
  name: postgres-initdb-script
data:
  init.sql: {{ printf "CREATE USER keycloak WITH PASSWORD '%s';\nCREATE DATABASE bitnami_keycloak OWNER keycloak;" (include "keycloak.postgresPassword" .) | b64enc }}



